### ISSUE TITLE
runtime error after running 11 epochs

### ISSUE THREAD

**Issue by divyansharma** [HRNet/HRNet-Semantic-Segmentation#100]
I started train.py with config as "seg_hrnet_w18_small_v1_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml." Training stopped after running 11 epochs. It's showing  - RuntimeError: value cannot be converted to type float without overflow: (7.14568e-06,-2.32177e-06). Below is link for screenshot of error message.
<img width="933" alt="Capture132" src="https://user-images.githubusercontent.com/31931986/73912292-250e8380-48da-11ea-9f68-f20fd7160571.PNG">

**Comment by icesohelrana** [comment]
I'm having the same issue. How you have solved this issue?

**Comment by FoilHao** [comment]
@divyansharma I‘m having the same issue. I ran a few experiments, and they all raise this error in epoch 116/120. How did you solved the issue?
