### ISSUE TITLE
Dose it support coco datasets?

### ISSUE THREAD

**Issue by dzyjjpy** [HRNet/HRNet-Semantic-Segmentation#109]
The datasets used in repo such as cityscapes is not enough. Does it support coco datasets? could you pls give some advice about training HRNet for segmentation on coco?

**Comment by sunke123** [comment]
This paper try the HRNet on coco-stuff.
https://arxiv.org/abs/1909.11065

We have not tried on coco.

**Comment by dzyjjpy** [comment]
okay, thanks @sunke123
