### ISSUE TITLE
how does this model pretrain on imagenet?

### ISSUE THREAD

**Issue by argman** [HRNet/HRNet-Semantic-Segmentation#11]

**Comment by argman** [comment]
and whats transition layer in your code ? i think its used in red part ? but why need transition ? channels and feature size does not change between stages
![image](https://user-images.githubusercontent.com/15120999/58311444-933e1380-7e3b-11e9-9064-05af1ff70ac1.png)

**Comment by sunke123** [comment]
@argman 
We provide the code for pretraining HRNet on imagenet https://github.com/HRNet/HRNet-Image-Classification.

In the transition module, we will add a new branch , which has more channels and lower resolution.
