### ISSUE TITLE
Is this compatible with opencv-python 4.1.1.26?

### ISSUE THREAD

**Issue by songyuc** [HRNet/HRNet-Semantic-Segmentation#111]
Hi guys,
I tried installing the dependencies, but an error appeared as,

> ERROR: Could not find a version that satisfies the requirement opencv-python==3.4.1.15 (from -r requirements.txt (line 2)) (from versions: 3.4.2.17, 3.4.3.18, 3.4.4.19, 3.4.5.20, 3.4.6.27, 3.4.7.28, 3.4.8.29, 3.4.9.31, 4.0.0.21, 4.0.1.23, 4.0.1.24, 4.1.0.25, 4.1.1.26, 4.1.2.30, 4.2.0.32)
ERROR: No matching distribution found for opencv-python==3.4.1.15 (from -r requirements.txt (line 2))
So how can I solve this error?

Any idea or answer will be appreciated!

**Comment by Adyoshkin** [comment]
Try to replace opencv-python==3.4.1.15 with opencv-python==**3.4.2.17**

**Comment by songyuc** [comment]
Thank you @Adyoshkin for your kind answer.
And I solved it by creating an Anaconda environment of older version of Python 3.6.
