### ISSUE TITLE
The 2nd, 3rd, 4th stages contain 1, 4,3 multi-resolution blocks, respectively

### ISSUE THREAD

**Issue by miaoYuanyuan** [HRNet/HRNet-Semantic-Segmentation#12]
>  The 2nd, 3rd, 4th stages contain 1, 4,3 multi-resolution blocks, respectively
How to understand this?

**Comment by sunke123** [comment]
The computation complexity assignment has the influence on the final performance.
You can find the similar cases, such as ResNet, DenseNet and so on.
For example, ResNet-101, the \#block in different stages: 3, 4, 23, 3.

We didn't spend much time in adjusting that.
So, if you are interesting at that, you can try to change the assignment of blocks in our network.
