### ISSUE TITLE
A question about multi_scale_output

### ISSUE THREAD

**Issue by bigroad111** [HRNet/HRNet-Semantic-Segmentation#13]
In the file /lib/models/seg_hrnet.py, the 389th line indicates that multi_scale_output is used last module. However, the 390th line and the 391 line means that when multi_scale_output=False and i is the index of the last module, multi_scale_output is set False. So , i am confused with the condition for setting reset_multi_scale_output True.

**Comment by sunke123** [comment]
If you want to use only the high-resolution features, you can set the multi_scale_output as False.

**Comment by bigroad111** [comment]
Thank you very much！


 
---Original---

**Comment by ngunauj** [comment]
In fact, in this rep. multi_scale_output and reset_multi_scale_output are always True.
