### ISSUE TITLE
Is "HRNetV2-W18-Small-v2" SOTA for lightweight segmentation? 

### ISSUE THREAD

**Issue by InternetMaster1** [HRNet/HRNet-Semantic-Segmentation#133]
Wow congratulations for the amazing library!

I am looking to implement high-quality semantic segmentation on a mobile device for accurate human segmentation for still images (i.e. _non-realtime_). 

1) SOTA for light-weight?

I have been researching a lot of lightweight architectures/backbones for this purpose (HardNet, MobileNetV2, MobileNetV2plus, ShelfNet, FasterSeg, BiseNetV2, SINet, PortraitNet, etc, etc)

Could HRNetV2-W18-Small-v2 be considered SOTA for this task? It achieves mIOU of 76.2% on Cityscapes.

The mIOU of U-HarDNet-70 is 75.9% & it is at the top of[ paperswithcode SOTA list](https://paperswithcode.com/sota/real-time-semantic-segmentation-on-cityscapes) for real-time

2) Is the CityScapes leaderboard a good place to look for my task at hand? I am looking for human/person segmentation. Should I rather be looking for leaderboards of Coco or PASCAL? 

3) Is there "[HRNet + OCR + SegFix](https://github.com/HRNet/HRNet-Semantic-Segmentation/tree/HRNet-OCR)" option available for HRNetV2-W18-Small-v2? 

Thanks for your patience with the newbie questions!

**Comment by WaterKnight1998** [comment]
> Wow congratulations for the amazing library!
> 
> I am looking to implement high-quality semantic segmentation on a mobile device for accurate human segmentation for still images (i.e. _non-realtime_).
> 
> 1. SOTA for light-weight?
> 
> I have been researching a lot of lightweight architectures/backbones for this purpose (HardNet, MobileNetV2, MobileNetV2plus, ShelfNet, FasterSeg, BiseNetV2, SINet, PortraitNet, etc, etc)
> 
> Could HRNetV2-W18-Small-v2 be considered SOTA for this task? It achieves mIOU of 76.2% on Cityscapes.
> 
> The mIOU of U-HarDNet-70 is 75.9% & it is at the top of[ paperswithcode SOTA list](https://paperswithcode.com/sota/real-time-semantic-segmentation-on-cityscapes) for real-time
> 
> 1. Is the CityScapes leaderboard a good place to look for my task at hand? I am looking for human/person segmentation. Should I rather be looking for leaderboards of Coco or PASCAL?
> 2. Is there "[HRNet + OCR + SegFix](https://github.com/HRNet/HRNet-Semantic-Segmentation/tree/HRNet-OCR)" option available for HRNetV2-W18-Small-v2?
> 
> Thanks for your patience with the newbie questions!

Which heads have you tried??

**Comment by InternetMaster1** [comment]
Sorry, I am new to this. What do you mean by heads?

1) I have tried following library till now, it's based on DeeplabV3+ and Resnet50, but looks heavy for mobile usage. 
https://github.com/srihari-humbarwadi/person_segmentation_tf2.0

2) I even tried the Deeplabv3plus and Mobilenetv2 combo based on this library. 
https://github.com/nolanliou/mobile-deeplab-v3-plus/issues/11

That library owner recommended to use a better backbone to reach higher accuracy. 

Hence, I am trying to hunt a lightweight segmentation library which would help me achieve higher accuracy on the same training as compared to above mentioned libraries.

Thanks

**Comment by WaterKnight1998** [comment]
> Sorry, I am new to this. What do you mean by heads?
> 
> 1. I have tried following library till now, it's based on DeeplabV3+ and Resnet50, but looks heavy for mobile usage.
>    https://github.com/srihari-humbarwadi/person_segmentation_tf2.0
> 2. I even tried the Deeplabv3plus and Mobilenetv2 combo based on this library.
>    [nolanliou/mobile-deeplab-v3-plus#11](https://github.com/nolanliou/mobile-deeplab-v3-plus/issues/11)
> 
> That library owner recommended to use a better backbone to reach higher accuracy.
> 
> Hence, I am trying to hunt a lightweight segmentation library which would help me achieve higher accuracy on the same training as compared to above mentioned libraries.
> 
> Thanks

This arch has the backbone included. If you just want the backbone you should go to classification repo

**Comment by InternetMaster1** [comment]
No, not looking for just a backbone. 

Looking for the best arch+backbone combo for lightweight segmentation with high accuracy.

I was just just curious about HRNet vs HarDNet, and wanted opinion as to which would be considered a better option for my task...
