### ISSUE TITLE
What's the difference about the bn_momentum=0.1 or 0.01? Does it have a great effect on accuracy

### ISSUE THREAD

**Issue by zyXu1996** [HRNet/HRNet-Semantic-Segmentation#140]

**Comment by sunke123** [comment]
We use small bn_momentum to alleviate the fluctuation of BN statistics.
We find that bn_momentum=0.01 have a effect on LIP dataset, but not for cityscapes and pascal-ctx.

**Comment by Margrate** [comment]
> We use small bn_momentum to alleviate the fluctuation of BN statistics.
> We find that bn_momentum=0.01 have a effect on LIP dataset, but not for cityscapes and pascal-ctx.

bn_momentum =0.01 or bn_momentum=o.1  is better?
