### ISSUE TITLE
There seems to be no exchange/fuse in the transition layer according to the code

### ISSUE THREAD

**Issue by DragoniteDD** [HRNet/HRNet-Semantic-Segmentation#15]
I drew the architecture of HRNet according to the code.
[Architecture of High Resolution Net (HRNet).pdf](https://github.com/HRNet/HRNet-Semantic-Segmentation/files/3278076/Architecture.of.High.Resolution.Net.HRNet.pdf)
Not 100% confident that I am right but there seems to be no exchange/fuse across stages in the transition layers. The new branch is only generated from the closest branch, not fused with all previous branches. Can you take a look at that?
https://github.com/HRNet/HRNet-Semantic-Segmentation/blob/master/lib/models/seg_hrnet.py#L332-L345
In addition, for segmentation tasks, as mentioned in #2 by some other developer, I was wondering how do you match the output resolution to original image since the output resolution is 1/4 in both width and height? Do you upsample the output or upsample all the final feature maps?
Thank you! Impressive Work!

**Comment by sunke123** [comment]
Thanks for your attention.

You are right. We upsample the final output resolution to the original resolution by bilinear interpolation. 

And I think there are some misunderstandings.
1. The second conv layer in the basic block outputs C channels (not 4C).
2. We adopt conv1x1 + bilinear interpolation to upsample the low-resolution representations (not conv3x3 shown as the orange arrow).

As for the fusion, you can refer to this issue 
HRNet/HRNet-Object-Detection#3

**Comment by DragoniteDD** [comment]
whoops, thank you for pointing out. That 4C & conv3x3 are typo result from copy/paste. Thank you for reading the graph carefully and pointing them out.

One more thing to confirm. Regarding the fusion, it is true that your current default implementation for segmentation contains only 1 module in each stage (according to the default model configuration file), thus only 1 within-stage fusion (or can be called inter-stage fusion since it is at the end of the stage and it connects the transition layer)? i.e. Is the fusion part of my plot correct for the default segmentation model?

Thank you very much for the fast & careful reply. I really appreciate it.

**Comment by sidml** [comment]
If anyone else is wondering, how to train the model if the model output size is not equal to label size, check out  [this](https://github.com/HRNet/HRNet-Semantic-Segmentation/blob/77044e60b6d71489465531ea60ba209b63145bcc/lib/core/criterion.py#L22).
