### ISSUE TITLE
subprocess.CalledProcessError: Command returned non-zero exit status 1

### ISSUE THREAD

**Issue by sakura-iv** [HRNet/HRNet-Semantic-Segmentation#160]
Hello, when I ran train.py by using
 

> python -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml

I met an error:

> Traceback (most recent call last):
>   File "tools/train.py", line 295, in <module>
>     main()
>   File "tools/train.py", line 99, in main
>     backend="nccl", init_method="env://",
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
>     store, rank, world_size = next(rendezvous(url))
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
>     store = TCPStore(master_addr, master_port, world_size, start_daemon)
> **RuntimeError: Address already in use**
> Traceback (most recent call last):
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
>     main()
>   File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
>     cmd=process.args)
> **subprocess.CalledProcessError: Command '['/home/zhh/anaconda3/envs/py3.6/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml']' returned non-zero exit status 1.**

This is very similar with issue #32 , but in that issue this error seems not to be solved.
my pytorch version is 1.1.0, and my python version is 3.6.2, how should I solve this problem ?

**Comment by qifyin** [comment]
RuntimeError: Address already in use.  The problem is easy.  Following code is for you:
python -m torch.distributed.launch --nproc_per_node=4 --master_port=29501 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml.  The difference is "--master_port=29501"

**Comment by sakura-iv** [comment]
oh, I got it ! Thank you very much !
