### ISSUE TITLE
Inconsistent size between output and target

### ISSUE THREAD

**Issue by YN-Tang** [HRNet/HRNet-Semantic-Segmentation#17]
Hi, congrats on your great work.

I was trying to experimenting with your proposed code on a dataset other than cityscape, where I set the input image shape to be 512x512. But I see that with your default settings for the network, the output has a shape of 128x128, so do I have to add the code for upsampling manually based on your implementation? 
I might me dumb somehow, but I don't see where to adjust the output shape.

Regards.

**Comment by EternallyTruth** [comment]
I have the same confusion ! 
Before the `Bottleneck`, 2  convolution layers with stride 2 make the input down sample 4x. Should I up sample 4x after the final layer to recover the input size or change the stride of the first two convolution layer into 1 ?

**Comment by YN-Tang** [comment]
I guess you might wanna check out other issues, the similar questions have been asked for a few times. But, my question is, put the bilinear upsampling layer before the final layer or after? cuz I believe if the final output comes from a bilinear upsampling layer, the output has to be a bit coarse.

**Comment by DragoniteDD** [comment]
Based on the author's reply here, it seems to be bilinear interpolation upsampling after the output
https://github.com/HRNet/HRNet-Semantic-Segmentation/issues/15#issuecomment-501100510

**Comment by EternallyTruth** [comment]
Thanks for your reply. I've seen the issue. But it seems to be a little coarse to bilinear 4x to predict directly. I want to know whether you have some solutions to address it?

**Comment by sidml** [comment]
If anyone else is wondering, how to train the model if the model output size is not equal to label size, check out  [this](https://github.com/HRNet/HRNet-Semantic-Segmentation/blob/77044e60b6d71489465531ea60ba209b63145bcc/lib/core/criterion.py#L22)

**Comment by NickLucche** [comment]
Hey, another place where you might want to take a look at is the initial strided convolution "block" https://github.com/HRNet/HRNet-Semantic-Segmentation/blob/77044e60b6d71489465531ea60ba209b63145bcc/lib/models/seg_hrnet.py#L414-L419 which effectively downscales the original input resolution; although editing it should be considered an architectural change, you can get your input resolution to stay constant.
