### ISSUE TITLE
Why is `nn.ReLU(inplace=False)` set for most activations?

### ISSUE THREAD

**Issue by huanglianghua** [HRNet/HRNet-Semantic-Segmentation#19]
Hi, thanks for the work. I notice that in the backbone's code, the `nn.ReLU` layers are with `inplace=False`, which differ from the implementation of `deep-high-resolution-pose-estimation` and other HRNet codes, where `inplace` are set to True.
Is this for specific reasons? Thanks.

**Comment by sunke123** [comment]
If using the InplaceABN, you need to set inplace=False.
You can try the official sync-bn provided by Pytorch.

**Comment by huanglianghua** [comment]
Gotta. Thanks a lot!
