### ISSUE TITLE
checkpoints.pth.tar is getting corrupted

### ISSUE THREAD

**Issue by GutlapalliNikhil** [HRNet/HRNet-Semantic-Segmentation#197]
When training was happening, I tried to download and open the checkpoints.pth.tar file. But I was getting that the file was corrupted. The data regarding epochs and pth was loading to the file, but I am not able to UnTAR the file. 

Can I know what I need to do. Please help.

Thanks and Regards,
Nikhil

**Comment by GutlapalliNikhil** [comment]
Did anyone has the same issue?

**Comment by StuvX** [comment]
Hi Nikhil, I don't think that the checkpoint files are actual tar format that can be UnTAR-ed. Instead you want to load the model using something like:

checkpoint = torch.load('checkpoints.pth.tar', map_location=device)... 

subsequently the weights that are loaded can be accessed in the ordered dict and loaded into the model using model.load_state_dict(checkpoint)

Hope that helps!

**Comment by GutlapalliNikhil** [comment]
Thank you @StuvX. I thought we only load the .pth file. Thanks.
