### ISSUE TITLE
Graph vs code differences

### ISSUE THREAD

**Issue by bhack** [HRNet/HRNet-Semantic-Segmentation#2]
I think that the graph and the code are not in sync.
In the graph seems that the yellow branch maintain the original resolution (there is no stride symbol on the yellow branch) but instead the yellow branch have stride on the first two yellow blocks so the output is 1/4 and so orange is 1/8.
Then you need to up-sample in inference.

![image](https://user-images.githubusercontent.com/1710528/57077296-faa8ed80-6ceb-11e9-8935-4d79db96db9e.png)

https://github.com/HRNet/HRNet-Semantic-Segmentation/blob/master/lib/models/seg_hrnet.py#L267-L271

**Comment by sunke123** [comment]
You are right. The yellow is 1/4..
We omit the stem in the figures.

**Comment by bhack** [comment]
This require also upsampling at eval and also this is not understand in the graph

**Comment by sunke123** [comment]
We use the same architecture in different tasks, such as pose estimation, semantic segmentation, object detection and facial landmark detection.
Following the prior works, we obtain the predictions from 1/4 for pose estimation and facial landmark detection and from original resolution for segmentation.
We provide the clear description in our papers.

**Comment by bhack** [comment]
Yes I know that it is in the paper but you have a stride conv specific  symbol in the diagram and so people think that you are not striding in yellow blocks other than going down to the next row. This is not true cause you need to use the stride symbol over the yellow branch itself.
