### ISSUE TITLE
need your help

### ISSUE THREAD

**Issue by sde123** [HRNet/HRNet-Semantic-Segmentation#21]
@sunke123 
Thank you very much for your work.
I see your code has a greet performance in cityscapes. Could you please show us those result files which you submit to the sityscapes?

**Comment by sde123** [comment]
@sunke123 
Could you please tell me what the berlin_000123_000019*.ext mean in the cityscapes website?I only have results .png not .ext file. Thank you!

**Comment by sunke123** [comment]
Please read the official instruction carefully.
".ext" is different for different task, ".png" for semantic segmentation.

![image](https://user-images.githubusercontent.com/11239351/59974197-d080f700-95db-11e9-999b-01cfa3026b84.png)

**Comment by sde123** [comment]
@sunke123 
Thank you for your reply! 
Could you please show me a example of this .ext file of any one different task?
If possible ,Could you please submit these example to google drive or any other website?
Thank you very much !
Looking forward to your reply!

**Comment by sunke123** [comment]
@sde123 
When you test our models on cityscapes, the results are saved as png files.
You can submit these files to the official website, and get the performance.

**Comment by sde123** [comment]
@sunke123 
Thank you for your reply.
Do you mean that I just need submit the png files to the cityscipe website, do not need any other txt file if I test your models on sityscipe dataset?
looking forward to your reply.

**Comment by sunke123** [comment]
@sde123 
Yes. You can try it.

**Comment by sde123** [comment]
@sunke123 
Thanks for your help.
But when I run your code, I got a error:
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1. 
Could you please tell me how to solve it?
Thank you very much!
