### ISSUE TITLE
请问您有用coco数据集做预训练？

### ISSUE THREAD

**Issue by GuangyanZhang** [HRNet/HRNet-Semantic-Segmentation#27]
我看了deeplabv3+，他用了coco数据集做预训练，请问你有用这个数据集做预训练吗？效果能提高多少呢？

**Comment by sunke123** [comment]
We don't use the coco data to pre-train the model.

**Comment by ngunauj** [comment]
Have you tried to train the seg network directly without using the imagenet pretrain model? What is the result?

**Comment by GuangyanZhang** [comment]
no, I'm training voc2012 dataset now.
