### ISSUE TITLE
Why use abn instead of bn?

### ISSUE THREAD

**Issue by zhoulukuan** [HRNet/HRNet-Semantic-Segmentation#28]
Is it because abn has a big help in saving memory? Will it improve performance?

**Comment by sunke123** [comment]
I have tried to replace the ABN with the official sync-bn of pytorch1-v1.1 and got the same performance.
I don't find that ABN saves memory or improve performance at least in our framework.

**Comment by ngunauj** [comment]
> I have tried to replace the ABN with the official sync-bn of pytorch1-v1.1 and got the same performance.

can you give some example of `the ABN with the official sync-bn of pytorch1-v1.1` ?   I am going crazy. Abn compilation is a big problem on my computer.

**Comment by sunke123** [comment]
@ngunauj 
I add a new branch named "pytorch-v1.1".
You can try that.

**Comment by zhoulukuan** [comment]
> @ngunauj
> I add a new branch named "pytorch-v1.1".
> You can try that.

In fact, I do the same experiment with you in anthor project and draw the same conclusion, so I am very confused.

**Comment by HH97** [comment]
@sunke123 
when running the branch "pytorch-v1.1", I got an error like this: 
`Number of Layers
Conv2d : 307 layers   BatchNorm2d : 306 layers   ReLU : 269 layers   Bottleneck : 4 layers   BasicBlock : 104 layers   HighResolutionModule : 8 layers   
Traceback (most recent call last):
  File "tools/train.py", line 286, in <module>
    main()
  File "tools/train.py", line 99, in main
    backend="nccl", init_method="env://"
  File "/home/hh/anaconda3/envs/hrtorch1/lib/python3.7/site-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/hh/anaconda3/envs/hrtorch1/lib/python3.7/site-packages/torch/distributed/rendezvous.py", line 119, in _env_rendezvous_handler
    raise _env_error("RANK")
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set`

Could you give me some advice?

**Comment by sunke123** [comment]
What's the conclusion?

**Comment by zhoulukuan** [comment]
> What's the conclusion?

The same performance. And cannot find it can save memory.

**Comment by ngunauj** [comment]
> > What's the conclusion?
> 
> The same performance. And cannot find it can save memory.

Have you used a pretrain model?

**Comment by zhoulukuan** [comment]
@ngunauj Yes. Model which use abn and other model which use normal bn both used pretrained model.
