### ISSUE TITLE
诡异错误AssertionError: Invalid device id

### ISSUE THREAD

**Issue by jwnirvana** [HRNet/HRNet-Semantic-Segmentation#30]
File "tools/train.py", line 171, in main
    model = nn.DataParallel(model, device_ids=gpus).cuda()
试了各种办法也没解决，求有相同问题的大佬点拨，谢谢！

**Comment by jwnirvana** [comment]
fixed

**Comment by zimratK** [comment]
Hi, I have the same issue, how did you solve this problem?

**Comment by richenyunqi** [comment]
The same error. Can you tell me how you can solve this error, please? thanks a lot!

**Comment by duanqg** [comment]
The same error. Can you tell me how you can solve this error, please? thanks a lot!
