### ISSUE TITLE
using   'Pytorch-v1.1' verison code

### ISSUE THREAD

**Issue by cch2016** [HRNet/HRNet-Semantic-Segmentation#32]

**Comment by cch2016** [comment]
I meet this error:
Traceback (most recent call last):
  File "tools/train.py", line 292, in <module>
    main()
  File "tools/train.py", line 116, in main
    scale_factor=config.TRAIN.SCALE_FACTOR)
TypeError: 'module' object is not callable
Traceback (most recent call last):
  File "tools/train.py", line 292, in <module>
Traceback (most recent call last):
  File "tools/train.py", line 292, in <module>
    main()
  File "tools/train.py", line 116, in main
Traceback (most recent call last):
  File "tools/train.py", line 292, in <module>
    scale_factor=config.TRAIN.SCALE_FACTOR)
TypeError: 'module' object is not callable
    main()
  File "tools/train.py", line 116, in main
    main()
  File "tools/train.py", line 116, in main
    scale_factor=config.TRAIN.SCALE_FACTOR)
TypeError: 'module' object is not callable
    scale_factor=config.TRAIN.SCALE_FACTOR)
TypeError: 'module' object is not callable
Traceback (most recent call last):
  File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml']' returned non-zero exit status 1.

**Comment by tjzjp** [comment]
> I meet this error:
> Traceback (most recent call last):
> File "tools/train.py", line 292, in
> main()
> File "tools/train.py", line 116, in main
> scale_factor=config.TRAIN.SCALE_FACTOR)
> TypeError: 'module' object is not callable
> Traceback (most recent call last):
> File "tools/train.py", line 292, in
> Traceback (most recent call last):
> File "tools/train.py", line 292, in
> main()
> File "tools/train.py", line 116, in main
> Traceback (most recent call last):
> File "tools/train.py", line 292, in
> scale_factor=config.TRAIN.SCALE_FACTOR)
> TypeError: 'module' object is not callable
> main()
> File "tools/train.py", line 116, in main
> main()
> File "tools/train.py", line 116, in main
> scale_factor=config.TRAIN.SCALE_FACTOR)
> TypeError: 'module' object is not callable
> scale_factor=config.TRAIN.SCALE_FACTOR)
> TypeError: 'module' object is not callable
> Traceback (most recent call last):
> File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in
> main()
> File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
> cmd=process.args)
> subprocess.CalledProcessError: Command '['/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml']' returned non-zero exit status 1.

I met the same problem, have you soloved it?
Maybe the cuda version?
Thank you very much!

**Comment by sakura-iv** [comment]
> Traceback (most recent call last):
  File "tools/train.py", line 288, in <module>
    main()
  File "tools/train.py", line 99, in main
    backend="nccl", init_method="env://",
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
    store, rank, world_size = next(rendezvous(url))
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
    store = TCPStore(master_addr, master_port, world_size, start_daemon)
RuntimeError: Address already in use
Traceback (most recent call last):
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in <module>
    main()
  File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
    cmd=process.args)
subprocess.CalledProcessError: Command '['/home/zhh/anaconda3/envs/py3.6/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml']' returned non-zero exit status 1.
> 

I met the same problem, how did you solve that ?

**Comment by pupu-chenyanyan** [comment]
hello ,How did you fix this?  I faced the same problem  @tjzjp

**Comment by pupu-chenyanyan** [comment]
> > Traceback (most recent call last):
> > File "tools/train.py", line 288, in 
> > main()
> > File "tools/train.py", line 99, in main
> > backend="nccl", init_method="env://",
> > File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 406, in init_process_group
> > store, rank, world_size = next(rendezvous(url))
> > File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 143, in _env_rendezvous_handler
> > store = TCPStore(master_addr, master_port, world_size, start_daemon)
> > RuntimeError: Address already in use
> > Traceback (most recent call last):
> > File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/runpy.py", line 85, in _run_code
> > exec(code, run_globals)
> > File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in 
> > main()
> > File "/home/zhh/anaconda3/envs/py3.6/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
> > cmd=process.args)
> > subprocess.CalledProcessError: Command '['/home/zhh/anaconda3/envs/py3.6/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml']' returned non-zero exit status 1.
> 
> I met the same problem, how did you solve that ?

I also met the same problem , can you tell me how to fix it ? thank you very much !

**Comment by pupu-chenyanyan** [comment]
> > I meet this error:
> > Traceback (most recent call last):
> > File "tools/train.py", line 292, in
> > main()
> > File "tools/train.py", line 116, in main
> > scale_factor=config.TRAIN.SCALE_FACTOR)
> > TypeError: 'module' object is not callable
> > Traceback (most recent call last):
> > File "tools/train.py", line 292, in
> > Traceback (most recent call last):
> > File "tools/train.py", line 292, in
> > main()
> > File "tools/train.py", line 116, in main
> > Traceback (most recent call last):
> > File "tools/train.py", line 292, in
> > scale_factor=config.TRAIN.SCALE_FACTOR)
> > TypeError: 'module' object is not callable
> > main()
> > File "tools/train.py", line 116, in main
> > main()
> > File "tools/train.py", line 116, in main
> > scale_factor=config.TRAIN.SCALE_FACTOR)
> > TypeError: 'module' object is not callable
> > scale_factor=config.TRAIN.SCALE_FACTOR)
> > TypeError: 'module' object is not callable
> > Traceback (most recent call last):
> > File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> > "**main**", mod_spec)
> > File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/runpy.py", line 85, in _run_code
> > exec(code, run_globals)
> > File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in
> > main()
> > File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
> > cmd=process.args)
> > subprocess.CalledProcessError: Command '['/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml']' returned non-zero exit status 1.
> 
> I met the same problem, have you soloved it?
> Maybe the cuda version?
> Thank you very much!

I also met the same problem , can you tell me how to fix it ? thank you very much !

**Comment by pupu-chenyanyan** [comment]
> I meet this error:
> Traceback (most recent call last):
> File "tools/train.py", line 292, in
> main()
> File "tools/train.py", line 116, in main
> scale_factor=config.TRAIN.SCALE_FACTOR)
> TypeError: 'module' object is not callable
> Traceback (most recent call last):
> File "tools/train.py", line 292, in
> Traceback (most recent call last):
> File "tools/train.py", line 292, in
> main()
> File "tools/train.py", line 116, in main
> Traceback (most recent call last):
> File "tools/train.py", line 292, in
> scale_factor=config.TRAIN.SCALE_FACTOR)
> TypeError: 'module' object is not callable
> main()
> File "tools/train.py", line 116, in main
> main()
> File "tools/train.py", line 116, in main
> scale_factor=config.TRAIN.SCALE_FACTOR)
> TypeError: 'module' object is not callable
> scale_factor=config.TRAIN.SCALE_FACTOR)
> TypeError: 'module' object is not callable
> Traceback (most recent call last):
> File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/runpy.py", line 193, in _run_module_as_main
> "**main**", mod_spec)
> File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/runpy.py", line 85, in _run_code
> exec(code, run_globals)
> File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 235, in
> main()
> File "/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/lib/python3.6/site-packages/torch/distributed/launch.py", line 231, in main
> cmd=process.args)
> subprocess.CalledProcessError: Command '['/home/chenchunhong/miniconda3/envs/HRNet_torch1.1/bin/python', '-u', 'tools/train.py', '--local_rank=0', '--cfg', 'experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml']' returned non-zero exit status 1.

I also met the same problem , can you tell me how to fix it ? thank you very much !
