### ISSUE TITLE
ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable RANK expected, but not set

### ISSUE THREAD

**Issue by jianlong-yuan** [HRNet/HRNet-Semantic-Segmentation#35]

**Comment by luojung** [comment]
it  took place on my computer too

**Comment by sunke123** [comment]
Do you use the new training command?
python -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml

**Comment by luojung** [comment]
thank you!
This problem is solved
i missed the para "-m torch.distributed.launch --nproc_per_node=4"

**Comment by dreamPoet** [comment]
if I use 8GPU, shall I set nproc_per_node as 8? thx
