### ISSUE TITLE
May I ask how you compute the 'class_weight' of dataset Class Cityscapes?

### ISSUE THREAD

**Issue by YuxuanChen98** [HRNet/HRNet-Semantic-Segmentation#44]
Hi, I notice there is a member variable in class Cityscapes. I wonder how you figure out the result? 
![image](https://user-images.githubusercontent.com/42828324/63246487-5bf1ce00-c295-11e9-8f00-7104256e0a41.png)

**Comment by sunke123** [comment]
You can check the details as follows:
https://github.com/PkuRainBow/OCNet.pytorch/issues/14#issuecomment-451134346

**Comment by YuxuanChen98** [comment]
Thanks a lot!
