### ISSUE TITLE
Training got stuck while no log in cmd line

### ISSUE THREAD

**Issue by ehion** [HRNet/HRNet-Semantic-Segmentation#46]
Trainning job got  stuck when epochs greater than 150(epochs>150),config is followed the default seeting in yaml file and model trained by 4V100(branch pytorch1.1).I run about 4 times and this problem seems appear every time(python -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml.)

training job1,job2,job3,job4 stoped at 154 187 167 167 epochs(No error message,just got stuck)

**Comment by lyf6** [comment]
> Trainning job got stuck when epochs greater than 150(epochs>150),config is followed the default seeting in yaml file and model trained by 4V100(branch pytorch1.1).I run about 4 times and this problem seems appear every time(python tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml.)
> 
> training job1,job2,job3,job4 stoped at 154 187 167 167 epochs(No error message,just got stuck)

I also meet this problem, have you solved it?

**Comment by ehion** [comment]
> > Trainning job got stuck when epochs greater than 150(epochs>150),config is followed the default seeting in yaml file and model trained by 4V100(branch pytorch1.1).I run about 4 times and this problem seems appear every time(python tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml.)
> > training job1,job2,job3,job4 stoped at 154 187 167 167 epochs(No error message,just got stuck)
> 
> I also meet this problem, have you solved it?

Haven't solved yet,this problem may occured due to the sync-bn in pytorch1.1,when i commented out 
`model = nn.SyncBatchNorm.convert_sync_batchnorm(model)` in train.py ,there no stuck.......

**Comment by lyf6** [comment]
> > > Trainning job got stuck when epochs greater than 150(epochs>150),config is followed the default seeting in yaml file and model trained by 4V100(branch pytorch1.1).I run about 4 times and this problem seems appear every time(python tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml.)
> > > training job1,job2,job3,job4 stoped at 154 187 167 167 epochs(No error message,just got stuck)
> > 
> > 
> > I also meet this problem, have you solved it?
> 
> Haven't solved yet,this problem may occured due to the sync-bn in pytorch1.1,when i commented out
> `model = nn.SyncBatchNorm.convert_sync_batchnorm(model)` in train.py ,there no stuck but Best_mIoU become lower than the baseline.......

thank you, I will try

**Comment by ehion** [comment]
I fix this bug by update pytorch version from pytorch1.1 to pytorch1.2 and there is no stuck now.
