### ISSUE TITLE
I have some doubts about the training results.

### ISSUE THREAD

**Issue by ngunauj** [HRNet/HRNet-Semantic-Segmentation#47]
Which yaml file is used to train it? and get the resule mIou:81.1
  
| model | Train Set | Test Set |#Params | GFLOPs | OHEM | Multi-scale| Flip | mIoU | 
| :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | 
| HRNetV2-W48 | Train | Val | 65.8M | 696.2 | No | No | No | 81.1 |

**Comment by ngunauj** [comment]
I can find 4 yamls in https://github.com/HRNet/HRNet-Semantic-Segmentation/tree/master/experiments/cityscapes .Which one do you use?

**Comment by sunke123** [comment]
seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml

**Comment by ngunauj** [comment]
> seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml

@sunke123 but this yaml. Flip is True....  so this  

| model | Train Set | Test Set |#Params | GFLOPs | OHEM | Multi-scale| Flip | mIoU | 
| :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | :--: | 
| HRNetV2-W48 | Train | Val | 65.8M | 696.2 | No | No | No | 81.1 |

所以上面的结果是seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml 中将flip设置为false得到的？

**Comment by sunke123** [comment]
TEST_FLIP=False, not the FLIP for training.

**Comment by ngunauj** [comment]
> TEST_FLIP=False, not the FLIP for training.

ok, thanks

**Comment by Margrate** [comment]
> Which yaml file is used to train it? and get the resule mIou:81.1
> 
> model	Train Set	Test Set	#Params	GFLOPs	OHEM	Multi-scale	Flip	mIoU
> HRNetV2-W48	Train	Val	65.8M	696.2	No	No	No	81.1

Can you reach 81.1%? I  just got 80.84%
