### ISSUE TITLE
questions about LIP dataset labels.

### ISSUE THREAD

**Issue by Nyquist0** [HRNet/HRNet-Semantic-Segmentation#48]
Hi, I didn't find the _'train_segmentations_reversed'_  labels of the LIP datasets.
Is this your pre-processed part? 
How can I get this? 
Thanks

**Comment by sunke123** [comment]
LIP provides the reversed annotations for the training data.
You can download the labels ("Train_parsing_reversed_labels.zip" in the https://drive.google.com/drive/folders/1ZjNrTb7T_SsOdck76qDcd5OHkFEU0C6Q).

**Comment by Nyquist0** [comment]
I can download it from this site.
Thanks a lot!

**Comment by HongChow** [comment]
> Hi, I didn't find the _'train_segmentations_reversed'_ labels of the LIP datasets.
> Is this your pre-processed part?
> How can I get this?
> Thanks

A stupid question： what‘s the reverse label mean？

**Comment by edwardyehuang** [comment]
> 
> 
> > Hi, I didn't find the _'train_segmentations_reversed'_ labels of the LIP datasets.
> > Is this your pre-processed part?
> > How can I get this?
> > Thanks
> 
> A stupid question： what‘s the reverse label mean？

Same question lol
