### ISSUE TITLE
transform the model into ScriptModules

### ISSUE THREAD

**Issue by toyal** [HRNet/HRNet-Semantic-Segmentation#49]
when i transform the hrnet model into ScriptModules using the command "traced_script_module=torch.jit.trace(kp_model,example)
    traced_script_module.save("hrnet_model.pt")" ,the error "assert(isinstance(orig, torch.nn.Module))   AssertionError" occur .i find it is caused by the 
![84](https://user-images.githubusercontent.com/27479107/64086366-594da900-cd6a-11e9-829e-f901148fd148.png),any suggestion

**Comment by hahahaprince** [comment]
I meet the same problem. Have you solved it?

**Comment by hahahaprince** [comment]
I solved this problem by edit **line 1300** of 'torch/jit/_init_.py'  as follow:
```python
        if not isinstance(orig, torch.nn.Module):
            self._name = orig.__name__
            orig = torch.nn.Module()
        else:
            self._name = 'TracedModule[' + type(orig).__name__ + ']'
```
to
```python
     if not isinstance(orig, torch.nn.Module):
            if orig is None:
                self._name = 'anyname'
            else:
                self._name = orig.__name__
            # self._name = orig.__name__
            orig = torch.nn.Module()
        else:
            self._name = 'TracedModule[' + type(orig).__name__ + ']'
```

**Comment by toyal** [comment]
> I solved this problem by edit **line 1300** of 'torch/jit/_init_.py' as follow:
> 
> ```python
>         if not isinstance(orig, torch.nn.Module):
>             self._name = orig.__name__
>             orig = torch.nn.Module()
>         else:
>             self._name = 'TracedModule[' + type(orig).__name__ + ']'
> ```
> 
> to
> 
> ```python
>      if not isinstance(orig, torch.nn.Module):
>             if orig is None:
>                 self._name = 'anyname'
>             else:
>                 self._name = orig.__name__
>             # self._name = orig.__name__
>             orig = torch.nn.Module()
>         else:
>             self._name = 'TracedModule[' + type(orig).__name__ + ']'
> ```

thank you ,i will try later

**Comment by WaterKnight1998** [comment]
> I solved this problem by edit **line 1300** of 'torch/jit/_init_.py' as follow:
> 
> ```python
>         if not isinstance(orig, torch.nn.Module):
>             self._name = orig.__name__
>             orig = torch.nn.Module()
>         else:
>             self._name = 'TracedModule[' + type(orig).__name__ + ']'
> ```
> 
> to
> 
> ```python
>      if not isinstance(orig, torch.nn.Module):
>             if orig is None:
>                 self._name = 'anyname'
>             else:
>                 self._name = orig.__name__
>             # self._name = orig.__name__
>             orig = torch.nn.Module()
>         else:
>             self._name = 'TracedModule[' + type(orig).__name__ + ']'
> ```

Is there a way of solving it without modifying torch.jit.script?

**Comment by zhangyaoying** [comment]
I use the torch version is 1.5, can't find this function on the 1300 lines
Can you tell me your version of the torch？Thank you very much

**Comment by Vozf** [comment]
This can also be fixed by changing None to identity in all `append(None)` There is at least 2 such lines the other one with `fuse_layer`  lines like this:
```
transition_layers.append(None)
```
to lines like this
```
transition_layers.append(torch.nn.Identity())
```

**Comment by 2017ND** [comment]
@Vozf yes, thanks very much!  I solved the problem through your way. 
   But there was an error when I loaded the .pt model. My code is as follows:

    torch::jit::script::Module module;
    try {
        module = torch::jit::load("../hrnet.pt");
    }
    catch (const c10::Error& e) {
        std::cerr << "error loading the model\n";
        return -1;
    }

Did you encounter this mistake?
