### ISSUE TITLE
Mistaken  reference

### ISSUE THREAD

**Issue by LinaShanghaitech** [HRNet/HRNet-Semantic-Segmentation#5]
Hi,
I've noticed that the result of  Deeplab on the LIP dataset comes from CE2P and CE2P 
cite the original value from JPPNet. 
[https://arxiv.org/pdf/1804.01984.pdf](url)
According to the references of this paper, it actually used the DeepLabV2 instead of DeepLabV3+ and you may need to correct this mistake?

**Comment by sunke123** [comment]
Thanks a lot.
I will correct that.
