### ISSUE TITLE
Image Size Issue

### ISSUE THREAD

**Issue by HamzaFarhan** [HRNet/HRNet-Semantic-Segmentation#52]
Due to the initial 2-stride convolutions, my output image size is (input image size) / 4.
Shouldn't the network have the same output size as the input?

**Comment by HamzaFarhan** [comment]
Sorry, I re-read the paper and found the solution.

**Comment by WaterKnight1998** [comment]
> Sorry, I re-read the paper and found the solution.

> The segmentation maps are upsampled (4 times) to the input
> size by bilinear upsampling for both training and testing.

Is it better to update the head of the model?
