### ISSUE TITLE
the size of trainning data

### ISSUE THREAD

**Issue by zhangyunming** [HRNet/HRNet-Semantic-Segmentation#53]
hi, i trained with my own data ,but the data are not in the same size, it need to resize all trainning data to same size? and the "base_size"in config need to set what if the training data size are not same.
thanks.

**Comment by sunke123** [comment]
In general, we tend to crop or resize the original images to a fixed input size, which is necessary for training with a large batch size.
The base_size is only a hyper-parameter, which is related to your data. You can set "base_size" as the maximum of your data size or the average value.
