### ISSUE TITLE
How can i visualize the predicted results

### ISSUE THREAD

**Issue by Epiphqny** [HRNet/HRNet-Semantic-Segmentation#56]
Thanks!

**Comment by 864546664** [comment]
have you solved it，thank you

**Comment by umairanis03** [comment]
Hi @864546664 Have you visualized the results ?

**Comment by 864546664** [comment]
> Hi @864546664 Have you visualized the results ?

for binary segement,you can use a score thresh to set pixels from model result under the thresh to 0，and then transform the result to 0 and 255，after these transformation，you can visualize the result。

**Comment by umairanis03** [comment]
Thanks, @864546664 for your reply

Basically I want to do inference on my custom images, which function did you use for it?

**Comment by 864546664** [comment]
> Thanks, @864546664 for your reply
> 
> Basically I want to do inference on my custom images, which function did you use for it?

i hava forgotten if the hrnet server a function to visualize results，you can write a function by yourself。
