### ISSUE TITLE
Run on a single GPU 

### ISSUE THREAD

**Issue by morawi** [HRNet/HRNet-Semantic-Segmentation#58]
Hi, 

what changes should I make to run:

` python -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml`

on a single Titan X GPU?

NB. I 've been trying and I am getting some errors related to Cuda and distribution.

Thanks in advance,

**Comment by sunke123** [comment]
python -m torch.distributed.launch **--nproc_per_node=1**

**Comment by stuhailiu** [comment]
@morawi @sunke123 Using this command to run the test.py file still has no output, could you tell me how to run on a single GPU? 

python -m torch.distributed.launch --nproc_per_node=1 tools/test.py --cfg experiments/cityscapes/seg_hrnet_w48_train_ohem_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml TEST.MODEL_FILE hrnet_w48_cityscapes_cls19_1024x2048_trainset.pth  TEST.SCALE_LIST 0.5,0.75,1.0,1.25,1.5,1.75  TEST.FLIP_TEST True
