### ISSUE TITLE
LIP Dataset Performance

### ISSUE THREAD

**Issue by PeikeLi** [HRNet/HRNet-Semantic-Segmentation#6]
Hi Ke,
Really good work and idea for the HRNet. I was trying to reproduce the performance on LIP dataset from your experiment yaml file. But only achieve 50.59% for the best mIoU.

> saving checkpoint to output/lip/seg_hrnet_w48_473x473_sgd_lr7e-3_wd5e-4_bs_40_epoch150checkpoint.pth.tar
Loss: 0.543, MeanIU:  0.5059, Best_mIoU:  0.5059
[0.86811489 0.63133359 0.6837422  0.38433764 0.29877409 0.66269771
 0.1957649  0.54022205 0.45206418 0.74160168 0.26058858 0.21910118
 0.20592365 0.7124526  0.57165922 0.61438857 0.55989074 0.55301222
 0.47372399 0.4895043 ]

The only thing I changed is that I reinstalled the sync-bn (https://github.com/mapillary/inplace_abn) using pytorch 1.0. Will there be any possible reasons for the gap?

**Comment by sunke123** [comment]
Hi, @PeikeLi 
I have not tried our method on pytorch 1.0.

Do you get the results during the training process?
There are some differences between the training and the testing process:
1. During the training process, I resize both the images and labels for quickly testing.
    During the testing process, I only resize the images and evaluate the predictions on the original size.
2. During the training process, I only evaluate the model on 2000 images (10000 in all). You can check the 
    TEST.NUM_SAMPLES in the yaml file.
3. Following the prior works, I adopt flip-testing, which is not used during the training process.

You can check the training log and testing log.
https://1drv.ms/f/s!Aus8VCZ_C_33gQxgHhdVycJJnN_0

**Comment by PeikeLi** [comment]
> Hi, @PeikeLi
> I have not tried our method on pytorch 1.0.
> 
> Do you get the results during the training process?
> There are some differences between the training and the testing process:
> 
> 1. During the training process, I resize both the images and labels for quickly testing.
>    During the testing process, I only resize the images and evaluate the predictions on the original size.
> 2. During the training process, I only evaluate the model on 2000 images (10000 in all). You can check the
>    TEST.NUM_SAMPLES in the yaml file.
> 3. Following the prior works, I adopt flip-testing, which is not used during the training process.
> 
> You can check the training log and testing log.
> https://1drv.ms/f/s!Aus8VCZ_C_33gQxgHhdVycJJnN_0

@sunke123  Thank you for your quick reply.
It seems like the training results are the same as yours. 
And one more question, I am quite curious why multi-scale testing method doesn't work on LIP dataset, which will certainly bring positive boost on another semantic segmentation tasks.

**Comment by PeikeLi** [comment]
Reproduce successfully! I will close this issue.

**Comment by zhouhao-learning** [comment]
@PeikeLi 
Hi, I would like to ask you to use the LIP data set training, have you encountered a Segmentation fault error, how do you solve it?

**Comment by PeikeLi** [comment]
@zhouhao-learning 
I didn't encounter such a problem. To my experience, you need to check your complinging environment and running environment, especially for some C-extension third-party package.

**Comment by zhouhao-learning** [comment]
@PeikeLi 
Ok, thank you for your suggestion.

**Comment by HongChow** [comment]
> Hi Ke,
> Really good work and idea for the HRNet. I was trying to reproduce the performance on LIP dataset from your experiment yaml file. But only achieve 50.59% for the best mIoU.
> 
> > saving checkpoint to output/lip/seg_hrnet_w48_473x473_sgd_lr7e-3_wd5e-4_bs_40_epoch150checkpoint.pth.tar
> > Loss: 0.543, MeanIU:  0.5059, Best_mIoU:  0.5059
> > [0.86811489 0.63133359 0.6837422  0.38433764 0.29877409 0.66269771
> > 0.1957649  0.54022205 0.45206418 0.74160168 0.26058858 0.21910118
> > 0.20592365 0.7124526  0.57165922 0.61438857 0.55989074 0.55301222
> > 0.47372399 0.4895043 ]
> 
> The only thing I changed is that I reinstalled the sync-bn (https://github.com/mapillary/inplace_abn) using pytorch 1.0. Will there be any possible reasons for the gap?

Hi， i have a stupid question： why different datasets need different environment？
