### ISSUE TITLE
train.py: error: unrecognized arguments: --local_rank=3 -m

### ISSUE THREAD

**Issue by haohuazhu** [HRNet/HRNet-Semantic-Segmentation#61]
zhuhaohua@hadoop:~/HRNet-Semantic-Segmentation1.0$ python -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yamlpython -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml
usage: train.py [-h] --cfg CFG ...
train.py: error: unrecognized arguments: --local_rank=1 -m
usage: train.py [-h] --cfg CFG ...
train.py: error: unrecognized arguments: --local_rank=0 -m
usage: train.py [-h] --cfg CFG ...
train.py: error: unrecognized arguments: --local_rank=2 -m
usage: train.py [-h] --cfg CFG ...
train.py: error: unrecognized arguments: --local_rank=3 -m

what should i do to solve the problme?

**Comment by sharatg9** [comment]
> zhuhaohua@hadoop:~/HRNet-Semantic-Segmentation1.0$ python -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yamlpython -m torch.distributed.launch --nproc_per_node=4 tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml
> usage: train.py [-h] --cfg CFG ...
> train.py: error: unrecognized arguments: --local_rank=1 -m
> usage: train.py [-h] --cfg CFG ...
> train.py: error: unrecognized arguments: --local_rank=0 -m
> usage: train.py [-h] --cfg CFG ...
> train.py: error: unrecognized arguments: --local_rank=2 -m
> usage: train.py [-h] --cfg CFG ...
> train.py: error: unrecognized arguments: --local_rank=3 -m
> 
> what should i do to solve the problme?

How did u slove this ??
