### ISSUE TITLE
No such file or directory :'json/trainval_merged.json'

### ISSUE THREAD

**Issue by haohuazhu** [HRNet/HRNet-Semantic-Segmentation#64]

**Comment by Jee-King** [comment]
I meet the same problem, how do you solve it?

**Comment by haohuazhu** [comment]
You have to download it from the dataset website(maybe?I forget it),in all,u have to download this file,you can search it by google.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"JeeKing"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月1日(星期五) 中午11:41
收件人:&nbsp;"HRNet/HRNet-Semantic-Segmentation"<HRNet-Semantic-Segmentation@noreply.github.com&gt;;
抄送:&nbsp;"stone"<871735607@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [HRNet/HRNet-Semantic-Segmentation] No such file or directory :'json/trainval_merged.json' (#64)




I meet the same problem, how do you solve it?
