### ISSUE TITLE
no results in task"Evaluating our model on the Cityscapes test set with multi-scale and flip testing"

### ISSUE THREAD

**Issue by haohuazhu** [HRNet/HRNet-Semantic-Segmentation#65]
it didn't turn out the result about miou,pixel_accureay,.etc.

**Comment by haohuazhu** [comment]
![capture_20191022163601578](https://user-images.githubusercontent.com/45006711/67270108-8a389780-f4ea-11e9-8f21-9a6c6efdb2f5.jpeg)

**Comment by haohuazhu** [comment]
I haven't got the answer yet,why did this problem be closed?

**Comment by welleast** [comment]
@haohuazhu can you provide more details about your question?

**Comment by sunke123** [comment]
@haohuazhu 

You should submit your predictions on test set to the official website. We have not the ground-truth of test set, and so we cannot provide any results.
