### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by lihongwei521** [HRNet/HRNet-Semantic-Segmentation#68]
when I run "python tools/test.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml                      DATASET.TEST_SET list/cityscapes/test.lst                      TEST.MODEL_FILE model/hrnet_w48_cityscapes_cls19_1024x2048_trainset.pth                      TEST.SCALE_LIST 0.5,0.75,1.0,1.25,1.5,1.75                      TEST.FLIP_TEST True " ,I encounter the problem "AttributeError: 'NoneType' object has no attribute 'shape' “，could you tell me how to solve it ? thanks a lot !

Traceback (most recent call last):
  File "tools/test.py", line 141, in <module>
    main()
  File "tools/test.py", line 133, in main
    sv_dir=final_output_dir)
  File "/home/lihongwei/myfile/project/HRNet_Segm/tools/../lib/core/function.py", line 158, in test
    for _, batch in enumerate(tqdm(testloader)):
  File "/opt/anaconda3/envs/torch041/lib/python3.6/site-packages/tqdm/std.py", line 1081, in __iter__
    for obj in iterable:
  File "/opt/anaconda3/envs/torch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/opt/anaconda3/envs/torch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
AttributeError: Traceback (most recent call last):
  File "/opt/anaconda3/envs/torch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/opt/anaconda3/envs/torch041/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/lihongwei/myfile/project/HRNet_Segm/tools/../lib/datasets/cityscapes.py", line 105, in __getitem__
    size = image.shape
AttributeError: 'NoneType' object has no attribute 'shape'

when i run  " python tools/test.py " on  DATASET.TEST_SET list/cityscapes/val.lst ,
python tools/test.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml                      DATASET.TEST_SET list/cityscapes/test.lst                      TEST.MODEL_FILE model/hrnet_w48_cityscapes_cls19_1024x2048_trainset.pth                      TEST.SCALE_LIST 0.5,0.75,1.0,1.25,1.5,1.75                      TEST.FLIP_TEST True
 it is no problem.  i don't known why?

**Comment by lihongwei521** [comment]
It is my data folder
├── data
│   ├── cityscapes
│   │   ├── gtFine
│   │   │   ├── test
│   │   │   ├── train
│   │   │   └── val
│   │   └── leftImg8bit
│   │       ├── test
│   │       ├── train
│   │       └── val
│   ├── lip
│   │   ├── TrainVal_images
│   │   │   ├── train_images
│   │   │   └── val_images
│   │   └── TrainVal_parsing_annotations
│   │       ├── train_segmentations
│   │       ├── train_segmentations_reversed
│   │       └── val_segmentations
│   └── list
│       ├── cityscapes
│       │   ├── test.lst
│       │   ├── train.lst
│       │   ├── trainval.lst
│       │   └── val.lst
│       └── lip
│           ├── testvalList.txt
│           ├── trainList.txt
│           └── valList.txt

**Comment by huangfuts** [comment]
hello, I'm tring the HRNet code as with you. But when running "python tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml", I encounter the problem "ninja: build stopped: subcommand failed.". How about you? Are you encounter the same problem? If No, can you tell me you some suggestions? In addition, how do you install the packet "ninja",? the way:pip install ninja? if OK, I really hope to contact with you.

**Comment by huangfuts** [comment]
my email: 1072319209@qq.com

**Comment by lihongwei521** [comment]
yeah,i encounter your problem when i use pytorch1.0/1.1/1.2 and cuda 10.0,&nbsp; &nbsp;i can't find the way to solve this problem.&nbsp; so I changed the environment "pytorch 0.4.1 and CUDA9.2" , then "ninja: build stopped: subcommand failed" don't happend.&nbsp;
i used "pip install ninja"




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "notifications"<notifications@github.com&gt;; 
发送时间: 2019年11月4日(星期一) 下午2:42
收件人: "HRNet/HRNet-Semantic-Segmentation"<HRNet-Semantic-Segmentation@noreply.github.com&gt;; 
抄送: "李洪伟"<896039315@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [HRNet/HRNet-Semantic-Segmentation] AttributeError: &#39;NoneType&#39; object has no attribute &#39;shape&#39; (#68)




my email: 1072319209@qq.com

**Comment by lihongwei521** [comment]
> hello, I'm tring the HRNet code as with you. But when running "python tools/train.py --cfg experiments/cityscapes/seg_hrnet_w48_train_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml", I encounter the problem "ninja: build stopped: subcommand failed.". How about you? Are you encounter the same problem? If No, can you tell me you some suggestions? In addition, how do you install the packet "ninja",? the way:pip install ninja? if OK, I really hope to contact with you.

yeah,I met the same problem as you when i used pytorch1.0 or 1.1or 1.2 and cuda 10.0.   i can't find the way to solve this problem.  so I changed the environment "pytorch 0.4.1 and CUDA9.2" , then "ninja: build stopped: subcommand failed" don't happend.
i used "pip install ninja"

**Comment by huangfuts** [comment]
First, thanks very much! 
my pytorch is 1.1.0 and cuda is 10.0. But regrettably the server used is public and cannot be changed. Sadly......
Anyhow, thanks a lot again! good luck to you!
