### ISSUE TITLE
debug branch pytorch1.1.0

### ISSUE THREAD

**Issue by zccyman** [HRNet/HRNet-Semantic-Segmentation#69]
How to debug branch pytorch1.1.0 using pycharm or vscode, we known this code use distributed training?

**Comment by dreamPoet** [comment]
I run it successfully.

**Comment by WangZhiKang77** [comment]
I also have the same question. Can't debug currently.

**Comment by dzyjjpy** [comment]
@sunke123 same question. How can we debug when using distributed training?
I can train successfully with command line with cityscapes.   want to train with custom datasets in cityscapes format
But when I debug with pycharm, errors displayed like beblow:

`/home/jiapy/virtualEnv/py3.6torch1.1/bin/python3.6 -m torch.distributed.launch --nproc_per_node=1 /home/adminroot/pycharm-community-2019.1.3/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 46067 --file /home/jiapy/workspace/segmentation/HRNet-Semantic-Segmentation/tools/train.py --cfg experiments/cityscapes/seg_hrnet_w18_small_v2_512x1024_sgd_lr1e-2_wd5e-4_bs_12_epoch484.yaml --local_rank=3
Traceback (most recent call last):
  File "/home/adminroot/pycharm-community-2019.1.3/helpers/pydev/pydevd.py", line 1593, in main
    setup = process_command_line(sys.argv)
  File "/home/adminroot/pycharm-community-2019.1.3/helpers/pydev/_pydevd_bundle/pydevd_command_line_handling.py", line 145, in process_command_line
    raise ValueError("Unexpected option: " + argv[i])
ValueError: Unexpected option: --local_rank=0
Usage:
pydevd.py --port N [(--client hostname) | --server] --file executable [file_options]

Process finished with exit code 0`

**Comment by li-Yongpeng** [comment]
I meet same question, and successfully debug the code through this link[https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003879119-how-to-run-python-m-command-in-pycharm-](url)

**Comment by li-Yongpeng** [comment]
I meet same question, and successfully debug the code through this [link](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003879119-how-to-run-python-m-command-in-pycharm-)

**Comment by PkuRainBow** [comment]
You can debug the code by setting the number of processes/GPUs as 1 under the distributed training scheme provided by Pytorch1.1+.
