### ISSUE TITLE
Whether the results can be better or worse if we replace the nearest neigbor resize into transpose convolution operation?

### ISSUE THREAD

**Issue by yeephycho** [HRNet/HRNet-Semantic-Segmentation#72]
Thank you for this excellent work!
If there's any experiments supporting any conclusion of above question, please let us know ：）

**Comment by sunke123** [comment]
We have not tried to replace the bilinear upsampling with the transpose convolution in segmentation. So, there is not any conclusion of your question.
I have tried this on classification, which introduces more parameters and flops and also achieves improvement.
Hope it will be helpful to you.

**Comment by yeephycho** [comment]
Noted with thanks!
