### ISSUE TITLE
Single class segmentation

### ISSUE THREAD

**Issue by dulex123** [HRNet/HRNet-Semantic-Segmentation#73]
If I have only one class segmentation (lets say a cat and background) is that NUM_CLASSES = 2 or 1? I cant run training if I use LIP-like config with NUM_CLASSES=1 or 2. I guess it's due to something on the output of the network? It perhaps should be 1 but it gets squeezed?

This is the output error
`/opt/conda/conda-bld/pytorch_1556653114079/work/aten/src/THCUNN/SpatialClassNLLCriterion.cu:103: void cunn_SpatialClassNLLCriterion_updateOutput_kernel(T *, T *, T *, long *, T *, int, int, int, int, int, long) [with T = float, AccumT = float]: block: [0,0,0], thread: [799,0,0] Assertion `t >= 0 && t < n_classes` failed.
`

**Comment by sunke123** [comment]
Hi, sorry for late rely.
You can try NUM_CLASS=2 and your ground-truth should only contain 0 or 1.
