### ISSUE TITLE
训练时间问题   The training time

### ISSUE THREAD

**Issue by suay1113** [HRNet/HRNet-Semantic-Segmentation#74]
您可以告诉我 原文在哪种GPU下进行的训练吗？

我在Titan GTX显卡  24G显存训练情况下

输入尺寸为576 * 576， 单卡batch size为2
输入尺寸为512 * 512， 单卡batch size为6
输入尺寸为400 * 400， 单卡batch size为8

这是正常现象吗？

Could you tell me what kind of GPU you use?
In the case of GPU Titan GTX （24g）
Input size is 576 * 576, batch size each is 2
Input size is 512 * 512, batch size is 6
Input size is 400 * 400, and the batch size is 8
Is this normal?

**Comment by sunke123** [comment]
For example, we train W48 with the input size of 512x1024 on 4 16G P100 GPUs (3 images per-gpu).
