### ISSUE TITLE
Is there any tool for human pose label?

### ISSUE THREAD

**Issue by xvolica** [HRNet/HRNet-Semantic-Segmentation#75]
请问除了labelme之外有适合人体关键点标注的工具吗？尤其是可以和这个工程中COCO或MPII格式对接的。
Is there any tool for human pose label? I want to find a tool which can convert label between coco format or mpii format.

**Comment by welleast** [comment]
Thanks a lot for your question! We also do not know any other tools. But the format conversion should not be so difficult.
