### ISSUE TITLE
Hello author! My criterion remain unchanged during the training.......

### ISSUE THREAD

**Issue by ysssgdhr** [HRNet/HRNet-Semantic-Segmentation#77]
I am training on my own seg data. It is a binary class liver cancer segmentation dataset. 
The input resolution is 512*512.
I've modified the code to run my own dataset, but criterion remains unchanged....

I wonder why the mIOU remains 0.5 and loss remain 0 ..........

![image](https://user-images.githubusercontent.com/24486813/70905270-6e5ef700-203e-11ea-91f9-ecb406a478e8.png)

**Comment by ysssgdhr** [comment]
光看代码实在是看不出为什么mIOU一直是0.5.......
希望作者大大能指点一二，指个方向也行

**Comment by ysssgdhr** [comment]
另外还有另一个问题。
读入的图片的mean和std的标准化参数我是直接借用的lip数据集的。我正在计算自己数据集的相关超参数（数据集太庞大了）。这三个数参数的顺序应该是按照opencv的BGR顺序来的吧，并没有在您的代码里看到转换成RGB的步骤。

**Comment by sunke123** [comment]
I have no experiences of liver cancer segmentation and cannot give any advice.
I guess that you can double-check your ground-truth and visualize your predictions. Maybe all the values in predictions are zero.

The normalization coefficients is for RGB. https://github.com/HRNet/HRNet-Semantic-Segmentation/blob/f9cb81695cb64da08b20807759a3794fc1339975/lib/datasets/base_dataset.py#L42

**Comment by ysssgdhr** [comment]
Thank you for your reply! As expected, it is the ground truth that has the problem. The label is 255 instead of 1. = =

**Comment by dreamlychina** [comment]
> el is 255 instea

大佬，能请教下你怎么训练自己的数据集？？
