### ISSUE TITLE
Performance on Pascal Context

### ISSUE THREAD

**Issue by AtsukiOsanai** [HRNet/HRNet-Semantic-Segmentation#78]
In HRNet paper, you provide two kinds of scores in Table3.
According to your configuration(experiments/pascal_ctx), you train 59 and 60 classes respectively.
My question is about performance gap between 59 and 60 classes, which has about 6% mIoU difference.

In EncNet, their performance gap is smaller than yours.
They calculate 59 classes mIoU(mIoU_59) first, and then get mIoU_60 by following formula;
mIoU_60 = mIoU_59 * 59 / 60.
(https://github.com/zhanghang1989/PyTorch-Encoding/issues/179)
Strictly speaking, I think EncNet formula is not correct.

So my questions are;
- How do you calculate mIoU_59 and mIoU_60 ?
- Do you think EncNet formula correct ?

I'd like to compare my network result with SOTA, but I'm confused there might be some metric on this dataset.
Thanks.

**Comment by sunke123** [comment]
Same as you. I think EncNet formula is wired. So, we don't adopt the EncNet formula to calculate the mIoU for 60 classes.

We calculate the same mIoU formula for 59 and 60 classes.

**Comment by AtsukiOsanai** [comment]
Thank you for replying.
I could understand your formula exactly.

Now I conclude that EncNet formula is one possible way to deal with this task.
Output over 59 classes means that they give up predicting back ground class.
Even if all the back ground pixels are treated as miss-labeled, its performance is better.
Because the back ground class of Pascal Context dataset includes a few hundreds of classes, the network might be confusing to distinguish it.

Thanks.

**Comment by Margrate** [comment]
I got mIoU=51.42 (59 classes) and mIoU=46.58(60 classes) which was a great gap compared with paper

![image](https://user-images.githubusercontent.com/42362411/131627663-9574e8bb-8bca-419f-b6a0-1bd210ac17bb.png)
