### ISSUE TITLE
The size of origin prediction

### ISSUE THREAD

**Issue by ysssgdhr** [HRNet/HRNet-Semantic-Segmentation#79]
Sorry to bother, here is some ques about Hrnet. I trained the netword on my custom data. The input size is 512*512.
When I evalute the model by 'pred=model(image)' , I find the size of prediction is 128*128 which is very strange. Is the size of every prediction of HrnetV2 is **fixed to 128*128** , or **a quarter of**  original resolution ?

![image](https://user-images.githubusercontent.com/24486813/71269086-6c23d200-2389-11ea-882d-8114b05ad5b7.png)

**Comment by ysssgdhr** [comment]
Another thing that puzzles me is that, on the premise of ensuring that the pixel value of the input label is 0 and 1, the range of the prediction mask obtained by the trained model using " pred=model'image' " in the test phase is in a very strange range: [-5.68,5.68].
![image](https://user-images.githubusercontent.com/24486813/71392969-327eef80-2645-11ea-8a7c-15d60bd946e7.png)
![image](https://user-images.githubusercontent.com/24486813/71392972-3579e000-2645-11ea-9995-d3b7856c15cf.png)

I was curious how such a model could be trained with labels from 0 to 1 (both training and testing were preprocessed using the same mean and std ) , which forced me to use 0 as a threshold to split the results.

If I use the default test way for other datasets : " multi_scale_inference ", the range of predicted values will be even larger and weirder, in [0,600].

![image](https://user-images.githubusercontent.com/24486813/71393026-75d95e00-2645-11ea-8bd8-2ea276ec36ba.png)
![image](https://user-images.githubusercontent.com/24486813/71393030-78d44e80-2645-11ea-9c71-f9ac3c2eca3f.png)

I have checked my code again and again to ensure that the value of the entered label is 0 and 1. May I ask if my prediction method is wrong  ? @sunke123

**Comment by ysssgdhr** [comment]
The origin image:
![image](https://user-images.githubusercontent.com/24486813/71393068-b20cbe80-2645-11ea-84f3-d377b8837dfd.png)

**Comment by ysssgdhr** [comment]
May I ask if the predicted label is distributed between 0 and 1 or not when the model is training on LIP or PASCAL ?
I still cannot sort it out why the value of predicted pixel can be 4\5 or more .....    @sunke123

**Comment by sunke123** [comment]
Hi, these images may be corrupt. I cannot check it.

Our network surely gives 1/4 resolution predictions, where upsampling the predictions to the original resolution is not included in the network. You can upsample the prediction by yourself or add the upsampling operation after the output of our network.

During training, the predictions is normalized to [0-1] by softmax. During testing, I don't use the softmax and then results in the wired range (just score outputed by network).

We just map each pixel to a class of the highest prediction score. So, softmax is not necessary during testing.

**Comment by ysssgdhr** [comment]
> Hi, these images may be corrupt. I cannot check it.
> Our network surely gives 1/4 resolution predictions, where upsampling the predictions to the original resolution is not included in the network. You can upsample the prediction by yourself or add the upsampling operation after the output of our network.
> During training, the predictions is normalized to [0-1] by softmax. During testing, I don't use the softmax and then results in the wired range (just score outputed by network).
> We just map each pixel to a class of the highest prediction score. So, softmax is not necessary during testing.

Thank you for your answers very much . All my questions have been answered

**Comment by Mps24-7uk** [comment]
@ysssgdhr I am struggling to train HRNet on my own dataset with 1 class. Can you help me with the steps you followed while training?
