### ISSUE TITLE
ImportError: No module named 'inplace_abn'

### ISSUE THREAD

**Issue by Smoltbob** [HRNet/HRNet-Semantic-Segmentation#8]
Even though I downloaded inplace_abn, I cannot import it.
Is there an additional step to make ? Is this because inplace_abn switched to pytorch 1.0 ? 
Thanks

**Comment by sunke123** [comment]
Our code includes the files of inplace_abn. You can check the lib/models/sync_bn.

If you want to use the new version of inplace_abn on pytorch 1.0, please follow the official instruction of inplace_abn.

**Comment by rudylyh** [comment]
Your inplace_abn module is not successfully compiled. You should have a library name inplace_abn.so in the directory /tmp/torch_extension/inplace_abn if everything goes well. It is compiled by gcc+cuda+ninja+torch. Last time I fixed this problem by updating cuda from 9.0 to 10.0
