### ISSUE TITLE
训练数据resize的一个疑问

### ISSUE THREAD

**Issue by taasoo** [HRNet/HRNet-Semantic-Segmentation#81]
请问，lip.py里训练数据读取后直接做了resize：
image, label = self.resize_image(image, label, self.crop_size)
如果image宽高不同，而crop_size为（473, 473），这里image就被拉伸变形了，直接输入到网络里训练会不会有问题呢？

**Comment by sunke123** [comment]
I agree.
This may be not a good image processing. We just follow the prior STOA approaches for a fair comparison.

You can try to find a better choice.

**Comment by taasoo** [comment]
Thank you！
