### ISSUE TITLE
有关特征融合的方式

### ISSUE THREAD

**Issue by ysssgdhr** [HRNet/HRNet-Semantic-Segmentation#84]
孙老师您的hrnet效果非常卓越，关于这个网络我有几个问题希望您能指点一二

1、hrnet和unet++的结构非常相似，但是在相关数据集上的效果好了10%都不止，难道都应该归功于更密集的跨层连接吗，您是怎么看的。

2、hrnet各层特征融合的方式非常简单，即相加Add。不知您有没有考虑过或者尝试过concatenate呢（concatenate的话可以方便添加scse注意力机制也许能进一步提升效果）。

**Comment by sunke123** [comment]
Yes, HRNet looks  similar to UNet++. But, there are some obvious differences between them.

1. As described in our paper, HRNet focuses on the high-resolution representation learning. We put more parameters/flops and increase the depth of high-resolution sub-network to improve the classification ability of high-resolution representations. UNet++ mainly utilizes the skip connections (or few of convs) to generate high-resolution representations, which is not enough for localization sensetive and pixel-level tasks.

2. As mentioned, we utilize more fusions to enrich the representation at each resolution, which improves the performance a lot. UNet++ only combines the low-resolution representations with high-resolution represnetations, but not using the high-resolution representations to improve the low-resolution representations. This also results in a lower performance.

We have not do more experiments to study the performance of concatenation, sum and so on. The concatenation will increase lots of memory cost and complexity in fusion。
You are welcome to improve our fusion or the whole architecture.

**Comment by ysssgdhr** [comment]
Your solution solves many of my puzzles. Thank you very much for your reply. :)
