### ISSUE TITLE
performance on pytorch1.1.0

### ISSUE THREAD

**Issue by dreamPoet** [HRNet/HRNet-Semantic-Segmentation#85]
Hi，

Is there any official evaluation of models on pytorch1.1.0? As I failed to train with pytorch0.4.1 so I use the branch code. thank you very much

Best

**Comment by DeppMeng** [comment]
Hi,

What do you mean by _official evaluation of models on pytorch1.1.0_? In  [Pytorch-v1.1 branch](https://github.com/HRNet/HRNet-Semantic-Segmentation/tree/pytorch-v1.1), both the codes and models are compatible with Pytorch 1.1, you can obtain correct result there.

**Comment by tjzjp** [comment]
I downloaded Pytorch-v1.1 branch, however it doesn't work because of the pytorch version. Could you tell me your pytorch version and cuda version?

**Comment by dreamPoet** [comment]
To be honest I ran it successfully with pytorch1.2.0 with Cuda 10.0 instead of pytorch1.1
