### ISSUE TITLE
Downloading HRNetV2-W48 + OCR

### ISSUE THREAD

**Issue by adrienju** [HRNet/HRNet-Semantic-Segmentation#87]
HI guys, 

I would like to download HRNetV2-W48 + OCR pretrained model from your repo but I have issues. 
I'm not a Chinese speaker and I don't have a baidu account, how can I download the ".pth" ? 

Thank you !

**Comment by hsfzxjy** [comment]
We have stored the pretrained model on both Google Drive and BaiduYun. Maybe you could download it from Google Drive.

**Comment by adrienju** [comment]
Oh sorry didn't see the google drive link ! Great job guys thank you
