### ISSUE TITLE
The download link for the cityscape smodel cannot be opened.Can you check it for me? Thank you.

### ISSUE THREAD

**Issue by mqchen1993** [HRNet/HRNet-Semantic-Segmentation#9]

**Comment by sunke123** [comment]
Hi @mqchen1993 , which one?
I have checked all the links.

**Comment by mqchen1993** [comment]
Thank you for replying so quickly, I can't open any of the cityscapes model. Can you open it on there? Maybe I can't get into onedrive.live.com. Here are the tips:
onedrive.live.com’s server IP address could not be found.

Is there any other downloadable way?Tanks!

**Comment by sunke123** [comment]
I have uploaded the models on baiduyun. You can try it.

**Comment by mqchen1993** [comment]
Thank you very much @sunke123  can I ask how much GPU memory you need to use at the time? My graphics card has 4 per 12G, but it is reported error during training: 
RuntimeError: CUDA error: out of memory

I am using the docker image you provided.kesun/pose:pytorch-0.4.1-bn-cudnn-off.

**Comment by sunke123** [comment]
I used 4 P100, 16G mem.
