### ISSUE TITLE
how can i train hrnet in one single GPU? thanks.

### ISSUE THREAD

**Issue by neverstoplearn** [HRNet/HRNet-Semantic-Segmentation#94]

**Comment by bengadisoufiane** [comment]
do you know how to use the output of the model to get the keypoints coordinates?

**Comment by neverstoplearn** [comment]
> do you know how to use the output of the model to get the keypoints coordinates?

sorry . i am in Semantic Segmentation

**Comment by bengadisoufiane** [comment]
but it is the same output, how to you use the output heatmap if you have any idea because we work on the same model.

thank you.

**Comment by nothingws** [comment]
.. I want to train this model based on a GPU, but I encountered this error..NameError: name '_get_default_group' is not defined.

**Comment by neverstoplearn** [comment]
you can try other unofficeal repository

**Comment by mucunwuxian** [comment]
Thank you very much for a great repository!

In my case, with the following changes, I could run on one GPU.
The data to be learned is LIP.

[Change 1 : seg_hrnet_w48_473x473_sgd_lr7e-3_wd5e-4_bs_40_epoch150.yaml]
```
(before)
GPUS: (0,1,2,3)
WORKERS: 4
|
v
(after)
GPUS: (0,)
WORKERS: 1
```

[Change 2 : train.py]
```
(before)
    if distributed:
        torch.cuda.set_device(args.local_rank)
        torch.distributed.init_process_group(
            backend="nccl", init_method="env://",
        )
|
v
(after)
    if (True):
        torch.cuda.set_device(args.local_rank)
        torch.distributed.init_process_group(
            backend="nccl", init_method="env://",
        )
```

[log on terminal]
```
Number of Layers
Conv2d : 307 layers   BatchNorm2d : 306 layers   ReLU : 269 layers   Bottleneck : 4 layers   BasicBlock : 104 layers   HighResolutionModule : 8 layers   
Epoch: [0/150] Iter:[0/7615], Time: 1.96, lr: 0.007000, Loss: 2.981129
Epoch: [0/150] Iter:[100/7615], Time: 0.40, lr: 0.006999, Loss: 1.904720
Epoch: [0/150] Iter:[200/7615], Time: 0.39, lr: 0.006999, Loss: 1.858579
Epoch: [0/150] Iter:[300/7615], Time: 0.39, lr: 0.006998, Loss: 1.826830
Epoch: [0/150] Iter:[400/7615], Time: 0.39, lr: 0.006998, Loss: 1.800535
Epoch: [0/150] Iter:[500/7615], Time: 0.39, lr: 0.006997, Loss: 1.795691
Epoch: [0/150] Iter:[600/7615], Time: 0.39, lr: 0.006997, Loss: 1.773056
Epoch: [0/150] Iter:[700/7615], Time: 0.39, lr: 0.006996, Loss: 1.760790
Epoch: [0/150] Iter:[800/7615], Time: 0.39, lr: 0.006996, Loss: 1.748990
Epoch: [0/150] Iter:[900/7615], Time: 0.39, lr: 0.006995, Loss: 1.742796
Epoch: [0/150] Iter:[1000/7615], Time: 0.40, lr: 0.006994, Loss: 1.732786
Epoch: [0/150] Iter:[1100/7615], Time: 0.40, lr: 0.006994, Loss: 1.720261
Epoch: [0/150] Iter:[1200/7615], Time: 0.40, lr: 0.006993, Loss: 1.714557
Epoch: [0/150] Iter:[1300/7615], Time: 0.40, lr: 0.006993, Loss: 1.706554
Epoch: [0/150] Iter:[1400/7615], Time: 0.40, lr: 0.006992, Loss: 1.699440
Epoch: [0/150] Iter:[1500/7615], Time: 0.40, lr: 0.006992, Loss: 1.691828
Epoch: [0/150] Iter:[1600/7615], Time: 0.40, lr: 0.006991, Loss: 1.684490
Epoch: [0/150] Iter:[1700/7615], Time: 0.40, lr: 0.006991, Loss: 1.675790
Epoch: [0/150] Iter:[1800/7615], Time: 0.40, lr: 0.006990, Loss: 1.669453
Epoch: [0/150] Iter:[1900/7615], Time: 0.40, lr: 0.006990, Loss: 1.666198
Epoch: [0/150] Iter:[2000/7615], Time: 0.40, lr: 0.006989, Loss: 1.661989
Epoch: [0/150] Iter:[2100/7615], Time: 0.40, lr: 0.006988, Loss: 1.656940
Epoch: [0/150] Iter:[2200/7615], Time: 0.40, lr: 0.006988, Loss: 1.653150
Epoch: [0/150] Iter:[2300/7615], Time: 0.40, lr: 0.006987, Loss: 1.648584
Epoch: [0/150] Iter:[2400/7615], Time: 0.40, lr: 0.006987, Loss: 1.643929
Epoch: [0/150] Iter:[2500/7615], Time: 0.40, lr: 0.006986, Loss: 1.639718
Epoch: [0/150] Iter:[2600/7615], Time: 0.40, lr: 0.006986, Loss: 1.637136
Epoch: [0/150] Iter:[2700/7615], Time: 0.40, lr: 0.006985, Loss: 1.634272
Epoch: [0/150] Iter:[2800/7615], Time: 0.40, lr: 0.006985, Loss: 1.630525
Epoch: [0/150] Iter:[2900/7615], Time: 0.40, lr: 0.006984, Loss: 1.627638
Epoch: [0/150] Iter:[3000/7615], Time: 0.40, lr: 0.006983, Loss: 1.623825
...
```

By the way, I just started running, so I do not know if I will run until the end...
This is just a short note to inform you.

**Comment by neverstoplearn** [comment]
thanks for your answer l. I will try it.

**Comment by mucunwuxian** [comment]
P.S.
I added prerequisites in #122 (https://github.com/HRNet/HRNet-Semantic-Segmentation/issues/122#issuecomment-612344804).
For your information!

**Comment by daodao1991** [comment]
> Thank you very much for a great repository!
> 
> In my case, with the following changes, I could run on one GPU.
> Learning data is LIP.
> 
> 
> [Change 1 : seg_hrnet_w48_473x473_sgd_lr7e-3_wd5e-4_bs_40_epoch150.yaml]
> 
> ```
> (before)
> GPUS: (0,1,2,3)
> WORKERS: 4
> |
> v
> (after)
> GPUS: (0,)
> WORKERS: 1
> ```
> 
> 
> [Change 2 : train.py]
> 
> ```
> (before)
>     if distributed:
>         torch.cuda.set_device(args.local_rank)
>         torch.distributed.init_process_group(
>             backend="nccl", init_method="env://",
>         )
> |
> v
> (after)
>     if (True):
>         torch.cuda.set_device(args.local_rank)
>         torch.distributed.init_process_group(
>             backend="nccl", init_method="env://",
>         )
> ```
> 
> 
> [log on terminal]
> 
> ```
> Number of Layers
> Conv2d : 307 layers   BatchNorm2d : 306 layers   ReLU : 269 layers   Bottleneck : 4 layers   BasicBlock : 104 layers   HighResolutionModule : 8 layers   
> Epoch: [0/150] Iter:[0/7615], Time: 1.96, lr: 0.007000, Loss: 2.981129
> Epoch: [0/150] Iter:[100/7615], Time: 0.40, lr: 0.006999, Loss: 1.904720
> Epoch: [0/150] Iter:[200/7615], Time: 0.39, lr: 0.006999, Loss: 1.858579
> Epoch: [0/150] Iter:[300/7615], Time: 0.39, lr: 0.006998, Loss: 1.826830
> Epoch: [0/150] Iter:[400/7615], Time: 0.39, lr: 0.006998, Loss: 1.800535
> Epoch: [0/150] Iter:[500/7615], Time: 0.39, lr: 0.006997, Loss: 1.795691
> Epoch: [0/150] Iter:[600/7615], Time: 0.39, lr: 0.006997, Loss: 1.773056
> Epoch: [0/150] Iter:[700/7615], Time: 0.39, lr: 0.006996, Loss: 1.760790
> Epoch: [0/150] Iter:[800/7615], Time: 0.39, lr: 0.006996, Loss: 1.748990
> Epoch: [0/150] Iter:[900/7615], Time: 0.39, lr: 0.006995, Loss: 1.742796
> Epoch: [0/150] Iter:[1000/7615], Time: 0.40, lr: 0.006994, Loss: 1.732786
> Epoch: [0/150] Iter:[1100/7615], Time: 0.40, lr: 0.006994, Loss: 1.720261
> Epoch: [0/150] Iter:[1200/7615], Time: 0.40, lr: 0.006993, Loss: 1.714557
> Epoch: [0/150] Iter:[1300/7615], Time: 0.40, lr: 0.006993, Loss: 1.706554
> Epoch: [0/150] Iter:[1400/7615], Time: 0.40, lr: 0.006992, Loss: 1.699440
> Epoch: [0/150] Iter:[1500/7615], Time: 0.40, lr: 0.006992, Loss: 1.691828
> Epoch: [0/150] Iter:[1600/7615], Time: 0.40, lr: 0.006991, Loss: 1.684490
> Epoch: [0/150] Iter:[1700/7615], Time: 0.40, lr: 0.006991, Loss: 1.675790
> Epoch: [0/150] Iter:[1800/7615], Time: 0.40, lr: 0.006990, Loss: 1.669453
> Epoch: [0/150] Iter:[1900/7615], Time: 0.40, lr: 0.006990, Loss: 1.666198
> Epoch: [0/150] Iter:[2000/7615], Time: 0.40, lr: 0.006989, Loss: 1.661989
> Epoch: [0/150] Iter:[2100/7615], Time: 0.40, lr: 0.006988, Loss: 1.656940
> Epoch: [0/150] Iter:[2200/7615], Time: 0.40, lr: 0.006988, Loss: 1.653150
> Epoch: [0/150] Iter:[2300/7615], Time: 0.40, lr: 0.006987, Loss: 1.648584
> Epoch: [0/150] Iter:[2400/7615], Time: 0.40, lr: 0.006987, Loss: 1.643929
> Epoch: [0/150] Iter:[2500/7615], Time: 0.40, lr: 0.006986, Loss: 1.639718
> Epoch: [0/150] Iter:[2600/7615], Time: 0.40, lr: 0.006986, Loss: 1.637136
> Epoch: [0/150] Iter:[2700/7615], Time: 0.40, lr: 0.006985, Loss: 1.634272
> Epoch: [0/150] Iter:[2800/7615], Time: 0.40, lr: 0.006985, Loss: 1.630525
> Epoch: [0/150] Iter:[2900/7615], Time: 0.40, lr: 0.006984, Loss: 1.627638
> Epoch: [0/150] Iter:[3000/7615], Time: 0.40, lr: 0.006983, Loss: 1.623825
> ...
> ```
> 
> 
> By the way, I just started running, so I do not know if I will run until the end...
> This is just a short note to inform you.

You should drop the part of Change 2. it's for muti-GPU training setup , just mak sure 'args.local_rank < 0' in the config file if u want to train on only one GPU.

**Comment by PkuRainBow** [comment]
Thanks for your interest in this work. Currently, most of the SOTA segmentation models are sensitive to the batch size (influences the Sync-BN statics). Therefore, we do not recommend to train the models with a single GPU from scratch.
