### ISSUE TITLE
why "Only Support SGD optimizer" ?

### ISSUE THREAD

**Issue by aisegmentcn** [HRNet/HRNet-Semantic-Segmentation#97]
If I can use adam as optimizer?

**Comment by sunke123** [comment]
Obviously, you can.
We only provide the implementation and reproduced performance with SGD optimizer.

If you want to use other optimizer, you need to modified the #epoch, the value of init lr and so on.

**Comment by aisegmentcn** [comment]
OK, thank you very much.
